development:
  adapter: postgresql
  encoding: unicode
  host: postgresql.s3s.lab
  database: express_entry_db
  username: ee_user
  password: ee_user
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>